context_size_1_ar_order_loss:
  _target_: src.tasks.metrics.ContextSize1AROrderLoss
  name: context_size_1_ar_order_loss
  update_key: context_size_1_ar_order_loss

context_size_2_ar_order_loss:
  _target_: src.tasks.metrics.ContextSize2AROrderLoss
  name: context_size_2_ar_order_loss
  update_key: context_size_2_ar_order_loss

context_size_1_out_of_order_loss:
  _target_: src.tasks.metrics.ContextSize1OutOfOrderLoss
  name: context_size_1_out_of_order_loss
  update_key: context_size_1_out_of_order_loss

context_size_2_out_of_order_loss:
  _target_: src.tasks.metrics.ContextSize2OutOfOrderLoss
  name: context_size_2_out_of_order_loss
  update_key: context_size_2_out_of_order_loss
